// <auto-generated />
using System;
using EcommerceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceAPI.Migrations
{
    [DbContext(typeof(EcommerceContextDB))]
    partial class EcommerceContextDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcommerceAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Electronic devices and gadgets",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Household items",
                            Name = "Home"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Apparel and garments",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sports equipment",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Printed and digital books",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Toys and games for kids",
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Beauty and personal care products",
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Food and household consumables",
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Home and office furniture",
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Car parts and accessories",
                            Name = "Automotive"
                        });
                });

            modelBuilder.Entity("EcommerceAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Laptop 8GB RAM, 256GB SSD",
                            Name = "HP Laptop 15",
                            Price = 700.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Wireless headphones with noise cancellation",
                            Name = "Bluetooth Headphones",
                            Price = 45.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "4K UHD Television",
                            Name = "50\" Smart TV",
                            Price = 450.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Ergonomic wireless mouse",
                            Name = "Wireless Mouse",
                            Price = 20.00m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "RGB backlit mechanical keyboard",
                            Name = "Mechanical Keyboard",
                            Price = 65.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "10000mAh power bank",
                            Name = "Portable Charger",
                            Price = 25.00m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Fitness tracking smartwatch",
                            Name = "Smartwatch",
                            Price = 120.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "10-inch tablet, 64GB storage",
                            Name = "Tablet 10 inch",
                            Price = 250.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "3-speed blender",
                            Name = "Oster Blender",
                            Price = 55.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "100% cotton sheets, queen size",
                            Name = "Bed Sheet Set",
                            Price = 30.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Bagless vacuum cleaner",
                            Name = "Vacuum Cleaner",
                            Price = 90.00m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "12-cup drip coffee maker",
                            Name = "Coffee Maker",
                            Price = 40.00m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "5.5L digital air fryer",
                            Name = "Air Fryer",
                            Price = 70.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "LED desk lamp with adjustable arm",
                            Name = "Table Lamp",
                            Price = 22.00m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Breathable t-shirt, size M",
                            Name = "Sports T-Shirt",
                            Price = 15.00m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "Straight-fit blue jeans",
                            Name = "Classic Jeans",
                            Price = 40.00m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "Unisex rain jacket",
                            Name = "Waterproof Jacket",
                            Price = 65.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "Lightweight running shoes",
                            Name = "Running Shoes",
                            Price = 55.00m,
                            Stock = 28
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Description = "Insulated winter coat",
                            Name = "Winter Coat",
                            Price = 85.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Description = "Adjustable cotton cap",
                            Name = "Baseball Cap",
                            Price = 12.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "Professional ball, size 5",
                            Name = "Soccer Ball",
                            Price = 25.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Description = "29-inch wheel bike, disc brakes",
                            Name = "Mountain Bike",
                            Price = 300.00m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Description = "Non-slip exercise yoga mat",
                            Name = "Yoga Mat",
                            Price = 18.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            Description = "Adjustable dumbbell set 20kg",
                            Name = "Dumbbell Set",
                            Price = 75.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            Description = "Lightweight aluminum tennis racket",
                            Name = "Tennis Racket",
                            Price = 45.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            Description = "Bestselling fiction paperback",
                            Name = "Fiction Novel",
                            Price = 14.00m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            Description = "Illustrated recipe cookbook",
                            Name = "Cookbook",
                            Price = 22.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 5,
                            Description = "Illustrated storybook for kids",
                            Name = "Children's Storybook",
                            Price = 10.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            Description = "Personal development guide",
                            Name = "Self-Help Guide",
                            Price = 16.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            Description = "200-piece building blocks",
                            Name = "Building Blocks Set",
                            Price = 28.00m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 6,
                            Description = "1:16 scale RC car",
                            Name = "Remote Control Car",
                            Price = 35.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 6,
                            Description = "1000-piece jigsaw puzzle",
                            Name = "Puzzle 1000 pieces",
                            Price = 15.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 6,
                            Description = "Family strategy board game",
                            Name = "Board Game",
                            Price = 30.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 7,
                            Description = "Hydrating facial moisturizer",
                            Name = "Facial Moisturizer",
                            Price = 18.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 7,
                            Description = "Nourishing shampoo 500ml",
                            Name = "Shampoo",
                            Price = 10.00m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 7,
                            Description = "Eau de parfum 100ml",
                            Name = "Perfume",
                            Price = 60.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 9,
                            Description = "Compact wooden office desk",
                            Name = "Office Desk",
                            Price = 150.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 9,
                            Description = "Adjustable ergonomic office chair",
                            Name = "Ergonomic Chair",
                            Price = 180.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 10,
                            Description = "Dashboard car phone holder",
                            Name = "Car Phone Mount",
                            Price = 12.00m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 10,
                            Description = "Synthetic motor oil, 5 liters",
                            Name = "Motor Oil 5L",
                            Price = 35.00m,
                            Stock = 30
                        });
                });

            modelBuilder.Entity("EcommerceAPI.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SaleDate = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 845.00m
                        },
                        new
                        {
                            Id = 2,
                            SaleDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 1270.00m
                        },
                        new
                        {
                            Id = 3,
                            SaleDate = new DateTime(2026, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 411.00m
                        },
                        new
                        {
                            Id = 4,
                            SaleDate = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 630.00m
                        },
                        new
                        {
                            Id = 5,
                            SaleDate = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 330.00m
                        },
                        new
                        {
                            Id = 6,
                            SaleDate = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 572.00m
                        },
                        new
                        {
                            Id = 7,
                            SaleDate = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 295.00m
                        },
                        new
                        {
                            Id = 8,
                            SaleDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 195.00m
                        },
                        new
                        {
                            Id = 9,
                            SaleDate = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 489.00m
                        },
                        new
                        {
                            Id = 10,
                            SaleDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 529.00m
                        },
                        new
                        {
                            Id = 11,
                            SaleDate = new DateTime(2026, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 255.00m
                        },
                        new
                        {
                            Id = 12,
                            SaleDate = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 89.00m
                        },
                        new
                        {
                            Id = 13,
                            SaleDate = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 217.00m
                        },
                        new
                        {
                            Id = 14,
                            SaleDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 1090.00m
                        },
                        new
                        {
                            Id = 15,
                            SaleDate = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 45.00m
                        },
                        new
                        {
                            Id = 16,
                            SaleDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 570.00m
                        },
                        new
                        {
                            Id = 17,
                            SaleDate = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 401.00m
                        },
                        new
                        {
                            Id = 18,
                            SaleDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 780.00m
                        },
                        new
                        {
                            Id = 19,
                            SaleDate = new DateTime(2026, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 420.00m
                        },
                        new
                        {
                            Id = 20,
                            SaleDate = new DateTime(2026, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 690.00m
                        },
                        new
                        {
                            Id = 21,
                            SaleDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 435.00m
                        },
                        new
                        {
                            Id = 22,
                            SaleDate = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 832.00m
                        },
                        new
                        {
                            Id = 23,
                            SaleDate = new DateTime(2026, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 190.00m
                        },
                        new
                        {
                            Id = 24,
                            SaleDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 445.00m
                        },
                        new
                        {
                            Id = 25,
                            SaleDate = new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 116.00m
                        },
                        new
                        {
                            Id = 26,
                            SaleDate = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 386.00m
                        },
                        new
                        {
                            Id = 27,
                            SaleDate = new DateTime(2026, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 1565.00m
                        },
                        new
                        {
                            Id = 28,
                            SaleDate = new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 195.00m
                        },
                        new
                        {
                            Id = 29,
                            SaleDate = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 1300.00m
                        },
                        new
                        {
                            Id = 30,
                            SaleDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 335.00m
                        },
                        new
                        {
                            Id = 31,
                            SaleDate = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 662.00m
                        },
                        new
                        {
                            Id = 32,
                            SaleDate = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 468.00m
                        },
                        new
                        {
                            Id = 33,
                            SaleDate = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 430.00m
                        },
                        new
                        {
                            Id = 34,
                            SaleDate = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 190.00m
                        },
                        new
                        {
                            Id = 35,
                            SaleDate = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 76.00m
                        },
                        new
                        {
                            Id = 36,
                            SaleDate = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 3240.00m
                        },
                        new
                        {
                            Id = 37,
                            SaleDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 515.00m
                        },
                        new
                        {
                            Id = 38,
                            SaleDate = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 480.00m
                        },
                        new
                        {
                            Id = 39,
                            SaleDate = new DateTime(2026, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 280.00m
                        },
                        new
                        {
                            Id = 40,
                            SaleDate = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 1070.00m
                        });
                });

            modelBuilder.Entity("EcommerceAPI.Models.SaleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 8,
                            Quantity = 2,
                            SaleId = 1,
                            Subtotal = 500.00m,
                            UnitPrice = 250.00m
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Quantity = 2,
                            SaleId = 1,
                            Subtotal = 90.00m,
                            UnitPrice = 45.00m
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 18,
                            Quantity = 1,
                            SaleId = 1,
                            Subtotal = 55.00m,
                            UnitPrice = 55.00m
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 16,
                            Quantity = 5,
                            SaleId = 1,
                            Subtotal = 200.00m,
                            UnitPrice = 40.00m
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 28,
                            Quantity = 2,
                            SaleId = 2,
                            Subtotal = 20.00m,
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 3,
                            Quantity = 2,
                            SaleId = 2,
                            Subtotal = 900.00m,
                            UnitPrice = 450.00m
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 2,
                            Quantity = 5,
                            SaleId = 2,
                            Subtotal = 225.00m,
                            UnitPrice = 45.00m
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 6,
                            Quantity = 5,
                            SaleId = 2,
                            Subtotal = 125.00m,
                            UnitPrice = 25.00m
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 13,
                            Quantity = 4,
                            SaleId = 3,
                            Subtotal = 280.00m,
                            UnitPrice = 70.00m
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 35,
                            Quantity = 5,
                            SaleId = 3,
                            Subtotal = 50.00m,
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 27,
                            Quantity = 3,
                            SaleId = 3,
                            Subtotal = 66.00m,
                            UnitPrice = 22.00m
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 15,
                            Quantity = 1,
                            SaleId = 3,
                            Subtotal = 15.00m,
                            UnitPrice = 15.00m
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 28,
                            Quantity = 3,
                            SaleId = 4,
                            Subtotal = 30.00m,
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 22,
                            Quantity = 2,
                            SaleId = 4,
                            Subtotal = 600.00m,
                            UnitPrice = 300.00m
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 7,
                            Quantity = 1,
                            SaleId = 5,
                            Subtotal = 120.00m,
                            UnitPrice = 120.00m
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 6,
                            Quantity = 3,
                            SaleId = 5,
                            Subtotal = 75.00m,
                            UnitPrice = 25.00m
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 25,
                            Quantity = 3,
                            SaleId = 5,
                            Subtotal = 135.00m,
                            UnitPrice = 45.00m
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 3,
                            Quantity = 1,
                            SaleId = 6,
                            Subtotal = 450.00m,
                            UnitPrice = 450.00m
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 30,
                            Quantity = 4,
                            SaleId = 6,
                            Subtotal = 112.00m,
                            UnitPrice = 28.00m
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 35,
                            Quantity = 1,
                            SaleId = 6,
                            Subtotal = 10.00m,
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 40,
                            Quantity = 2,
                            SaleId = 7,
                            Subtotal = 70.00m,
                            UnitPrice = 35.00m
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 24,
                            Quantity = 1,
                            SaleId = 7,
                            Subtotal = 75.00m,
                            UnitPrice = 75.00m
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 37,
                            Quantity = 1,
                            SaleId = 7,
                            Subtotal = 150.00m,
                            UnitPrice = 150.00m
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 19,
                            Quantity = 2,
                            SaleId = 8,
                            Subtotal = 170.00m,
                            UnitPrice = 85.00m
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 6,
                            Quantity = 1,
                            SaleId = 8,
                            Subtotal = 25.00m,
                            UnitPrice = 25.00m
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 30,
                            Quantity = 3,
                            SaleId = 9,
                            Subtotal = 84.00m,
                            UnitPrice = 28.00m
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 24,
                            Quantity = 3,
                            SaleId = 9,
                            Subtotal = 225.00m,
                            UnitPrice = 75.00m
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 11,
                            Quantity = 2,
                            SaleId = 9,
                            Subtotal = 180.00m,
                            UnitPrice = 90.00m
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 5,
                            Quantity = 5,
                            SaleId = 10,
                            Subtotal = 325.00m,
                            UnitPrice = 65.00m
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 39,
                            Quantity = 2,
                            SaleId = 10,
                            Subtotal = 24.00m,
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 11,
                            Quantity = 2,
                            SaleId = 10,
                            Subtotal = 180.00m,
                            UnitPrice = 90.00m
                        },
                        new
                        {
                            Id = 32,
                            ProductId = 18,
                            Quantity = 3,
                            SaleId = 11,
                            Subtotal = 165.00m,
                            UnitPrice = 55.00m
                        },
                        new
                        {
                            Id = 33,
                            ProductId = 36,
                            Quantity = 1,
                            SaleId = 11,
                            Subtotal = 60.00m,
                            UnitPrice = 60.00m
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 15,
                            Quantity = 2,
                            SaleId = 11,
                            Subtotal = 30.00m,
                            UnitPrice = 15.00m
                        },
                        new
                        {
                            Id = 35,
                            ProductId = 21,
                            Quantity = 3,
                            SaleId = 12,
                            Subtotal = 75.00m,
                            UnitPrice = 25.00m
                        },
                        new
                        {
                            Id = 36,
                            ProductId = 26,
                            Quantity = 1,
                            SaleId = 12,
                            Subtotal = 14.00m,
                            UnitPrice = 14.00m
                        },
                        new
                        {
                            Id = 37,
                            ProductId = 21,
                            Quantity = 4,
                            SaleId = 13,
                            Subtotal = 100.00m,
                            UnitPrice = 25.00m
                        },
                        new
                        {
                            Id = 38,
                            ProductId = 14,
                            Quantity = 2,
                            SaleId = 13,
                            Subtotal = 44.00m,
                            UnitPrice = 22.00m
                        },
                        new
                        {
                            Id = 39,
                            ProductId = 32,
                            Quantity = 3,
                            SaleId = 13,
                            Subtotal = 45.00m,
                            UnitPrice = 15.00m
                        },
                        new
                        {
                            Id = 40,
                            ProductId = 26,
                            Quantity = 2,
                            SaleId = 13,
                            Subtotal = 28.00m,
                            UnitPrice = 14.00m
                        },
                        new
                        {
                            Id = 41,
                            ProductId = 36,
                            Quantity = 4,
                            SaleId = 14,
                            Subtotal = 240.00m,
                            UnitPrice = 60.00m
                        },
                        new
                        {
                            Id = 42,
                            ProductId = 35,
                            Quantity = 5,
                            SaleId = 14,
                            Subtotal = 50.00m,
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 43,
                            ProductId = 17,
                            Quantity = 4,
                            SaleId = 14,
                            Subtotal = 260.00m,
                            UnitPrice = 65.00m
                        },
                        new
                        {
                            Id = 44,
                            ProductId = 38,
                            Quantity = 3,
                            SaleId = 14,
                            Subtotal = 540.00m,
                            UnitPrice = 180.00m
                        },
                        new
                        {
                            Id = 45,
                            ProductId = 33,
                            Quantity = 1,
                            SaleId = 15,
                            Subtotal = 30.00m,
                            UnitPrice = 30.00m
                        },
                        new
                        {
                            Id = 46,
                            ProductId = 32,
                            Quantity = 1,
                            SaleId = 15,
                            Subtotal = 15.00m,
                            UnitPrice = 15.00m
                        },
                        new
                        {
                            Id = 47,
                            ProductId = 10,
                            Quantity = 4,
                            SaleId = 16,
                            Subtotal = 120.00m,
                            UnitPrice = 30.00m
                        },
                        new
                        {
                            Id = 48,
                            ProductId = 11,
                            Quantity = 5,
                            SaleId = 16,
                            Subtotal = 450.00m,
                            UnitPrice = 90.00m
                        },
                        new
                        {
                            Id = 49,
                            ProductId = 25,
                            Quantity = 5,
                            SaleId = 17,
                            Subtotal = 225.00m,
                            UnitPrice = 45.00m
                        },
                        new
                        {
                            Id = 50,
                            ProductId = 39,
                            Quantity = 3,
                            SaleId = 17,
                            Subtotal = 36.00m,
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            Id = 51,
                            ProductId = 30,
                            Quantity = 5,
                            SaleId = 17,
                            Subtotal = 140.00m,
                            UnitPrice = 28.00m
                        },
                        new
                        {
                            Id = 52,
                            ProductId = 8,
                            Quantity = 3,
                            SaleId = 18,
                            Subtotal = 750.00m,
                            UnitPrice = 250.00m
                        },
                        new
                        {
                            Id = 53,
                            ProductId = 35,
                            Quantity = 3,
                            SaleId = 18,
                            Subtotal = 30.00m,
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 54,
                            ProductId = 28,
                            Quantity = 1,
                            SaleId = 19,
                            Subtotal = 10.00m,
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 55,
                            ProductId = 11,
                            Quantity = 3,
                            SaleId = 19,
                            Subtotal = 270.00m,
                            UnitPrice = 90.00m
                        },
                        new
                        {
                            Id = 56,
                            ProductId = 30,
                            Quantity = 5,
                            SaleId = 19,
                            Subtotal = 140.00m,
                            UnitPrice = 28.00m
                        },
                        new
                        {
                            Id = 57,
                            ProductId = 33,
                            Quantity = 3,
                            SaleId = 20,
                            Subtotal = 90.00m,
                            UnitPrice = 30.00m
                        },
                        new
                        {
                            Id = 58,
                            ProductId = 7,
                            Quantity = 5,
                            SaleId = 20,
                            Subtotal = 600.00m,
                            UnitPrice = 120.00m
                        },
                        new
                        {
                            Id = 59,
                            ProductId = 10,
                            Quantity = 2,
                            SaleId = 21,
                            Subtotal = 60.00m,
                            UnitPrice = 30.00m
                        },
                        new
                        {
                            Id = 60,
                            ProductId = 24,
                            Quantity = 5,
                            SaleId = 21,
                            Subtotal = 375.00m,
                            UnitPrice = 75.00m
                        },
                        new
                        {
                            Id = 61,
                            ProductId = 1,
                            Quantity = 1,
                            SaleId = 22,
                            Subtotal = 700.00m,
                            UnitPrice = 700.00m
                        },
                        new
                        {
                            Id = 62,
                            ProductId = 39,
                            Quantity = 1,
                            SaleId = 22,
                            Subtotal = 12.00m,
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            Id = 63,
                            ProductId = 21,
                            Quantity = 3,
                            SaleId = 22,
                            Subtotal = 75.00m,
                            UnitPrice = 25.00m
                        },
                        new
                        {
                            Id = 64,
                            ProductId = 32,
                            Quantity = 3,
                            SaleId = 22,
                            Subtotal = 45.00m,
                            UnitPrice = 15.00m
                        },
                        new
                        {
                            Id = 65,
                            ProductId = 16,
                            Quantity = 1,
                            SaleId = 23,
                            Subtotal = 40.00m,
                            UnitPrice = 40.00m
                        },
                        new
                        {
                            Id = 66,
                            ProductId = 37,
                            Quantity = 1,
                            SaleId = 23,
                            Subtotal = 150.00m,
                            UnitPrice = 150.00m
                        },
                        new
                        {
                            Id = 67,
                            ProductId = 5,
                            Quantity = 2,
                            SaleId = 24,
                            Subtotal = 130.00m,
                            UnitPrice = 65.00m
                        },
                        new
                        {
                            Id = 68,
                            ProductId = 35,
                            Quantity = 4,
                            SaleId = 24,
                            Subtotal = 40.00m,
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 69,
                            ProductId = 9,
                            Quantity = 5,
                            SaleId = 24,
                            Subtotal = 275.00m,
                            UnitPrice = 55.00m
                        },
                        new
                        {
                            Id = 70,
                            ProductId = 34,
                            Quantity = 2,
                            SaleId = 25,
                            Subtotal = 36.00m,
                            UnitPrice = 18.00m
                        },
                        new
                        {
                            Id = 71,
                            ProductId = 39,
                            Quantity = 5,
                            SaleId = 25,
                            Subtotal = 60.00m,
                            UnitPrice = 12.00m
                        },
                        new
                        {
                            Id = 72,
                            ProductId = 28,
                            Quantity = 2,
                            SaleId = 25,
                            Subtotal = 20.00m,
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 73,
                            ProductId = 26,
                            Quantity = 5,
                            SaleId = 26,
                            Subtotal = 70.00m,
                            UnitPrice = 14.00m
                        },
                        new
                        {
                            Id = 74,
                            ProductId = 24,
                            Quantity = 4,
                            SaleId = 26,
                            Subtotal = 300.00m,
                            UnitPrice = 75.00m
                        },
                        new
                        {
                            Id = 75,
                            ProductId = 29,
                            Quantity = 1,
                            SaleId = 26,
                            Subtotal = 16.00m,
                            UnitPrice = 16.00m
                        },
                        new
                        {
                            Id = 76,
                            ProductId = 5,
                            Quantity = 1,
                            SaleId = 27,
                            Subtotal = 65.00m,
                            UnitPrice = 65.00m
                        },
                        new
                        {
                            Id = 77,
                            ProductId = 22,
                            Quantity = 5,
                            SaleId = 27,
                            Subtotal = 1500.00m,
                            UnitPrice = 300.00m
                        },
                        new
                        {
                            Id = 78,
                            ProductId = 38,
                            Quantity = 1,
                            SaleId = 28,
                            Subtotal = 180.00m,
                            UnitPrice = 180.00m
                        },
                        new
                        {
                            Id = 79,
                            ProductId = 15,
                            Quantity = 1,
                            SaleId = 28,
                            Subtotal = 15.00m,
                            UnitPrice = 15.00m
                        },
                        new
                        {
                            Id = 80,
                            ProductId = 4,
                            Quantity = 3,
                            SaleId = 29,
                            Subtotal = 60.00m,
                            UnitPrice = 20.00m
                        },
                        new
                        {
                            Id = 81,
                            ProductId = 15,
                            Quantity = 1,
                            SaleId = 29,
                            Subtotal = 15.00m,
                            UnitPrice = 15.00m
                        },
                        new
                        {
                            Id = 82,
                            ProductId = 5,
                            Quantity = 5,
                            SaleId = 29,
                            Subtotal = 325.00m,
                            UnitPrice = 65.00m
                        },
                        new
                        {
                            Id = 83,
                            ProductId = 3,
                            Quantity = 2,
                            SaleId = 29,
                            Subtotal = 900.00m,
                            UnitPrice = 450.00m
                        },
                        new
                        {
                            Id = 84,
                            ProductId = 32,
                            Quantity = 5,
                            SaleId = 30,
                            Subtotal = 75.00m,
                            UnitPrice = 15.00m
                        },
                        new
                        {
                            Id = 85,
                            ProductId = 14,
                            Quantity = 5,
                            SaleId = 30,
                            Subtotal = 110.00m,
                            UnitPrice = 22.00m
                        },
                        new
                        {
                            Id = 86,
                            ProductId = 35,
                            Quantity = 4,
                            SaleId = 30,
                            Subtotal = 40.00m,
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 87,
                            ProductId = 9,
                            Quantity = 2,
                            SaleId = 30,
                            Subtotal = 110.00m,
                            UnitPrice = 55.00m
                        },
                        new
                        {
                            Id = 88,
                            ProductId = 27,
                            Quantity = 1,
                            SaleId = 31,
                            Subtotal = 22.00m,
                            UnitPrice = 22.00m
                        },
                        new
                        {
                            Id = 89,
                            ProductId = 13,
                            Quantity = 4,
                            SaleId = 31,
                            Subtotal = 280.00m,
                            UnitPrice = 70.00m
                        },
                        new
                        {
                            Id = 90,
                            ProductId = 7,
                            Quantity = 3,
                            SaleId = 31,
                            Subtotal = 360.00m,
                            UnitPrice = 120.00m
                        },
                        new
                        {
                            Id = 91,
                            ProductId = 30,
                            Quantity = 1,
                            SaleId = 32,
                            Subtotal = 28.00m,
                            UnitPrice = 28.00m
                        },
                        new
                        {
                            Id = 92,
                            ProductId = 4,
                            Quantity = 4,
                            SaleId = 32,
                            Subtotal = 80.00m,
                            UnitPrice = 20.00m
                        },
                        new
                        {
                            Id = 93,
                            ProductId = 7,
                            Quantity = 3,
                            SaleId = 32,
                            Subtotal = 360.00m,
                            UnitPrice = 120.00m
                        },
                        new
                        {
                            Id = 94,
                            ProductId = 16,
                            Quantity = 2,
                            SaleId = 33,
                            Subtotal = 80.00m,
                            UnitPrice = 40.00m
                        },
                        new
                        {
                            Id = 95,
                            ProductId = 13,
                            Quantity = 5,
                            SaleId = 33,
                            Subtotal = 350.00m,
                            UnitPrice = 70.00m
                        },
                        new
                        {
                            Id = 96,
                            ProductId = 28,
                            Quantity = 3,
                            SaleId = 34,
                            Subtotal = 30.00m,
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 97,
                            ProductId = 12,
                            Quantity = 4,
                            SaleId = 34,
                            Subtotal = 160.00m,
                            UnitPrice = 40.00m
                        },
                        new
                        {
                            Id = 98,
                            ProductId = 29,
                            Quantity = 1,
                            SaleId = 35,
                            Subtotal = 16.00m,
                            UnitPrice = 16.00m
                        },
                        new
                        {
                            Id = 99,
                            ProductId = 36,
                            Quantity = 1,
                            SaleId = 35,
                            Subtotal = 60.00m,
                            UnitPrice = 60.00m
                        },
                        new
                        {
                            Id = 100,
                            ProductId = 1,
                            Quantity = 4,
                            SaleId = 36,
                            Subtotal = 2800.00m,
                            UnitPrice = 700.00m
                        },
                        new
                        {
                            Id = 101,
                            ProductId = 6,
                            Quantity = 4,
                            SaleId = 36,
                            Subtotal = 100.00m,
                            UnitPrice = 25.00m
                        },
                        new
                        {
                            Id = 102,
                            ProductId = 16,
                            Quantity = 4,
                            SaleId = 36,
                            Subtotal = 160.00m,
                            UnitPrice = 40.00m
                        },
                        new
                        {
                            Id = 103,
                            ProductId = 11,
                            Quantity = 2,
                            SaleId = 36,
                            Subtotal = 180.00m,
                            UnitPrice = 90.00m
                        },
                        new
                        {
                            Id = 104,
                            ProductId = 4,
                            Quantity = 1,
                            SaleId = 37,
                            Subtotal = 20.00m,
                            UnitPrice = 20.00m
                        },
                        new
                        {
                            Id = 105,
                            ProductId = 11,
                            Quantity = 4,
                            SaleId = 37,
                            Subtotal = 360.00m,
                            UnitPrice = 90.00m
                        },
                        new
                        {
                            Id = 106,
                            ProductId = 25,
                            Quantity = 3,
                            SaleId = 37,
                            Subtotal = 135.00m,
                            UnitPrice = 45.00m
                        },
                        new
                        {
                            Id = 107,
                            ProductId = 19,
                            Quantity = 4,
                            SaleId = 38,
                            Subtotal = 340.00m,
                            UnitPrice = 85.00m
                        },
                        new
                        {
                            Id = 108,
                            ProductId = 28,
                            Quantity = 2,
                            SaleId = 38,
                            Subtotal = 20.00m,
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            Id = 109,
                            ProductId = 36,
                            Quantity = 2,
                            SaleId = 38,
                            Subtotal = 120.00m,
                            UnitPrice = 60.00m
                        },
                        new
                        {
                            Id = 110,
                            ProductId = 4,
                            Quantity = 5,
                            SaleId = 39,
                            Subtotal = 100.00m,
                            UnitPrice = 20.00m
                        },
                        new
                        {
                            Id = 111,
                            ProductId = 38,
                            Quantity = 1,
                            SaleId = 39,
                            Subtotal = 180.00m,
                            UnitPrice = 180.00m
                        },
                        new
                        {
                            Id = 112,
                            ProductId = 4,
                            Quantity = 5,
                            SaleId = 40,
                            Subtotal = 100.00m,
                            UnitPrice = 20.00m
                        },
                        new
                        {
                            Id = 113,
                            ProductId = 38,
                            Quantity = 5,
                            SaleId = 40,
                            Subtotal = 900.00m,
                            UnitPrice = 180.00m
                        },
                        new
                        {
                            Id = 114,
                            ProductId = 31,
                            Quantity = 2,
                            SaleId = 40,
                            Subtotal = 70.00m,
                            UnitPrice = 35.00m
                        });
                });

            modelBuilder.Entity("EcommerceAPI.Models.Product", b =>
                {
                    b.HasOne("EcommerceAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EcommerceAPI.Models.SaleDetail", b =>
                {
                    b.HasOne("EcommerceAPI.Models.Product", "Product")
                        .WithMany("SaleDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceAPI.Models.Sale", "Sale")
                        .WithMany("SaleDetails")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("EcommerceAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EcommerceAPI.Models.Product", b =>
                {
                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("EcommerceAPI.Models.Sale", b =>
                {
                    b.Navigation("SaleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
